[build]
target = "riscv64imac-unknown-none-elf"

[target.riscv64imac-unknown-none-elf]
runner = "qemu-system-riscv64 -nographic -machine virt -bios none -kernel"
linker = "riscv64-unknown-linux-gnu-ld"
rustflags = [
  "-C",
  "link-arg=-Tlinker.ld",
]

[unstable]
build-std-features = ["compiler-builtins-mem"]
build-std = ["core", "compiler_builtins", "alloc"]